# Generated by Django 3.1.4 on 2020-12-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_products',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
